from flask import Flask, render_template_string, abort
import json

app = Flask(__name__)

# Load data from JSON file
with open("data.json", "r") as f:
    samples = {entry["id"]: entry for entry in json.load(f)}

TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Zillow RAG Sample {{ id }}</title>
  <style>
    body { font-family: sans-serif; margin: 2em; background: #f9f9f9; }
    .section { background: #fff; padding: 1em 1.5em; margin-bottom: 1.5em;
               border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }
    h2 { margin-top: 0; color: #444; }
    pre { background: #eee; padding: 1em; overflow-x: auto; border-radius: 5px; }
    .nav { margin-top: 2em; }
    .nav a, .nav select { margin-right: 10px; font-size: 16px; }
  </style>
</head>
<body>
  <div class="section">
    <h2>Question (User Input Prompt)</h2>
    <p>{{ sample["question"] }}</p>
  </div>
  <div class="section">
    <h2>Context Retrieved</h2>
    <pre><code>{{ sample["context"] }}</code></pre>
  </div>
  <div class="section">
    <h2>Answer generated by mistralai/Mistral-7B-Instruct-v0.1</h2>
    <p>{{ sample["answer"] }}</p>
  </div>

  <div class="nav">
    {% if id > 1 %}
      <a href="/sample/{{ id - 1 }}">⬅ Previous</a>
    {% endif %}
    {% if id < max_id %}
      <a href="/sample/{{ id + 1 }}">Next ➡</a>
    {% endif %}

    <label for="sample-select">Jump to:</label>
    <select id="sample-select" onchange="location = '/sample/' + this.value;">
      {% for sid in all_ids %}
        <option value="{{ sid }}" {% if sid == id %}selected{% endif %}>Sample {{ sid }}</option>
      {% endfor %}
    </select>
  </div>
</body>
</html>
"""

@app.route("/")
def index():
    links = "".join(f'<li><a href="/sample/{sid}">Sample {sid}</a></li>' for sid in sorted(samples))
    return f"<h2>All Samples</h2><ul>{links}</ul>"

@app.route("/sample/<int:id>")
def show_sample(id):
    sample = samples.get(id)
    if not sample:
        abort(404)
    all_ids = sorted(samples.keys())
    max_id = max(all_ids)
    return render_template_string(TEMPLATE, id=id, sample=sample, max_id=max_id, all_ids=all_ids)

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=True)

